name: Build and Release to Public Repo

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Get Version Name
        id: get_version
        shell: bash
        run: |
          source version.properties
          echo "version_name=${versionMajor}.${versionMinor}.${versionPatch}" >> $GITHUB_OUTPUT

      - name: Build MSI Installer
        env:
          FIREBASE_ANALYTICS_URL: ${{ secrets.FIREBASE_ANALYTICS_URL }}
          FIREBASE_SELLABLE_ITEMS_URL: ${{ secrets.FIREBASE_SELLABLE_ITEMS_URL }}
          FIREBASE_ANONYMOUS_AUTH_URL: ${{ secrets.FIREBASE_ANONYMOUS_AUTH_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: ./gradlew composeApp:packageReleaseMsi


      - name: Upload Release to Public Repository
        uses: softprops/action-gh-release@v2
        with:
          repository: aleksbalev/L2LootClientAppReleases
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            composeApp/build/compose/binaries/main-release/msi/L2Loot-${{ steps.get_version.outputs.version_name }}.msi
          body: |
            ## L2Loot ${{ github.ref_name }}
            
            ### Installation
            
            **Windows MSI Installer (Recommended):**
            - Download `L2Loot-${{ steps.get_version.outputs.version_name }}.msi`
            - Run the installer and follow the setup wizard
            - The app will be installed and a desktop shortcut will be created
            
            **Windows EXE Portable:**
            - Download `L2Loot-${{ steps.get_version.outputs.version_name }}.exe`
            - Extract and run the executable
            
            ### What's New
            - Add your release notes here
