name: Build and Create Releases

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  create-release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-windows:
    permissions: write-all
    runs-on: windows-latest
    needs: create-release
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Change wrapper permission
        run: chmod +x ./gradlew

      - name: Build .msi
        run: ./gradlew composeApp:packageReleaseMsi

      - name: Get Version Name
        id: get_version_name
        shell: bash
        run: echo "version_name=$(./.github/scripts/get_version_name.sh version.properties" >> GITHUB_OUTPUT

      - name: Upload Release MSI Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload-url: ${{ needs.create-release.outputs.output1 }}
          asset_path: composeApp/build/compose/binaries/main-release/msi/L2Loot-
          asset_name: l2loot-${{ github.ref_name }}.msi
          asset_content_type: application/octet-stream
